export type ProtestantBook = {
  id: string;
  name: string;
  testament: 'OT' | 'NT';
};

export const PROTESTANT_BOOKS: ProtestantBook[] = [
  { id: 'GEN', name: 'Genesis', testament: 'OT' },
  { id: 'EXO', name: 'Exodus', testament: 'OT' },
  { id: 'LEV', name: 'Leviticus', testament: 'OT' },
  { id: 'NUM', name: 'Numbers', testament: 'OT' },
  { id: 'DEU', name: 'Deuteronomy', testament: 'OT' },
  { id: 'JOS', name: 'Joshua', testament: 'OT' },
  { id: 'JDG', name: 'Judges', testament: 'OT' },
  { id: 'RUT', name: 'Ruth', testament: 'OT' },
  { id: '1SA', name: '1 Samuel', testament: 'OT' },
  { id: '2SA', name: '2 Samuel', testament: 'OT' },
  { id: '1KI', name: '1 Kings', testament: 'OT' },
  { id: '2KI', name: '2 Kings', testament: 'OT' },
  { id: '1CH', name: '1 Chronicles', testament: 'OT' },
  { id: '2CH', name: '2 Chronicles', testament: 'OT' },
  { id: 'EZR', name: 'Ezra', testament: 'OT' },
  { id: 'NEH', name: 'Nehemiah', testament: 'OT' },
  { id: 'EST', name: 'Esther', testament: 'OT' },
  { id: 'JOB', name: 'Job', testament: 'OT' },
  { id: 'PSA', name: 'Psalms', testament: 'OT' },
  { id: 'PRO', name: 'Proverbs', testament: 'OT' },
  { id: 'ECC', name: 'Ecclesiastes', testament: 'OT' },
  { id: 'SNG', name: 'Song of Songs', testament: 'OT' },
  { id: 'ISA', name: 'Isaiah', testament: 'OT' },
  { id: 'JER', name: 'Jeremiah', testament: 'OT' },
  { id: 'LAM', name: 'Lamentations', testament: 'OT' },
  { id: 'EZK', name: 'Ezekiel', testament: 'OT' },
  { id: 'DAN', name: 'Daniel', testament: 'OT' },
  { id: 'HOS', name: 'Hosea', testament: 'OT' },
  { id: 'JOL', name: 'Joel', testament: 'OT' },
  { id: 'AMO', name: 'Amos', testament: 'OT' },
  { id: 'OBA', name: 'Obadiah', testament: 'OT' },
  { id: 'JON', name: 'Jonah', testament: 'OT' },
  { id: 'MIC', name: 'Micah', testament: 'OT' },
  { id: 'NAM', name: 'Nahum', testament: 'OT' },
  { id: 'HAB', name: 'Habakkuk', testament: 'OT' },
  { id: 'ZEP', name: 'Zephaniah', testament: 'OT' },
  { id: 'HAG', name: 'Haggai', testament: 'OT' },
  { id: 'ZEC', name: 'Zechariah', testament: 'OT' },
  { id: 'MAL', name: 'Malachi', testament: 'OT' },
  { id: 'MAT', name: 'Matthew', testament: 'NT' },
  { id: 'MRK', name: 'Mark', testament: 'NT' },
  { id: 'LUK', name: 'Luke', testament: 'NT' },
  { id: 'JHN', name: 'John', testament: 'NT' },
  { id: 'ACT', name: 'Acts', testament: 'NT' },
  { id: 'ROM', name: 'Romans', testament: 'NT' },
  { id: '1CO', name: '1 Corinthians', testament: 'NT' },
  { id: '2CO', name: '2 Corinthians', testament: 'NT' },
  { id: 'GAL', name: 'Galatians', testament: 'NT' },
  { id: 'EPH', name: 'Ephesians', testament: 'NT' },
  { id: 'PHP', name: 'Philippians', testament: 'NT' },
  { id: 'COL', name: 'Colossians', testament: 'NT' },
  { id: '1TH', name: '1 Thessalonians', testament: 'NT' },
  { id: '2TH', name: '2 Thessalonians', testament: 'NT' },
  { id: '1TI', name: '1 Timothy', testament: 'NT' },
  { id: '2TI', name: '2 Timothy', testament: 'NT' },
  { id: 'TIT', name: 'Titus', testament: 'NT' },
  { id: 'PHM', name: 'Philemon', testament: 'NT' },
  { id: 'HEB', name: 'Hebrews', testament: 'NT' },
  { id: 'JAS', name: 'James', testament: 'NT' },
  { id: '1PE', name: '1 Peter', testament: 'NT' },
  { id: '2PE', name: '2 Peter', testament: 'NT' },
  { id: '1JN', name: '1 John', testament: 'NT' },
  { id: '2JN', name: '2 John', testament: 'NT' },
  { id: '3JN', name: '3 John', testament: 'NT' },
  { id: 'JUD', name: 'Jude', testament: 'NT' },
  { id: 'REV', name: 'Revelation', testament: 'NT' },
];

export function bookByName(name: string): ProtestantBook | undefined {
  return PROTESTANT_BOOKS.find((book) => book.name === name);
}
